server:
  servlet:
    context-path: /sistema
twilio:
  account_sid: AC634513ac9afa77e70e742fe029ad62f8
  auth_token: d53eb6b9f201bdb03f0424432094ce3c
  trial_number: +12565764221
spring:
  datasource:
    url: jdbc:mysql://localhost/ciudadonabd?useSSL=false&serverTimezone=GMT
    username: root
    password:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 60000
      maxLifetime: 60000
      maximumPoolSize: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  main:
     allow-circular-references: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: E:\\ServidorImagenes
  mail:
    host: smtp.gmail.com
    port: 587
    username: dona78073@gmail.com
    password: myxinyinvowcrdba 
logging:
  level:
    root: WARN
Jwt:
  password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkNpdWRhZGRvbmEiLCJpYXQiOjE1MTYyMzkwMjJ9.IXGg8s8QDLokLDoHEIfPCN1BxI6bvBeUD7Hy63m2bDE
